from flask import Flask, request, jsonify, make_response
from flask_restplus import Api,Resource,fields
#from sklearn.externals import joblib
import joblib
import numpy as np
import sys
import os


flask_app = Flask(__name__)      #creating flask WSGI Application
app = Api(app = flask_app,       #creating flask restplus api
		  version = "1.0", 
		  title = "Arrythmias Detection", 
		  description = "Predict cardiac Arrythmias")

name_space = app.namespace('prediction', description='Prediction APIs')

model = app.model('Prediction params', 
				  {'age': fields.Float,
				  'sex': fields.Float,
				  'height': fields.Float,
				  'weight': fields.Float,
				  'QRS_duration': fields.Float,
				  'P_R_interval': fields.Float,
				  'Q_T_interval': fields.Float,
				  'T_interval': fields.Float,
				  'P_interval': fields.Float,
				  'QRS': fields.Float,
				  'T': fields.Float,
				  'P': fields.Float,
				  'QRST': fields.Float,
				  'J': fields.Float,
				  'HR': fields.Float,
				  'DI_Q_wave': fields.Float,
				  'DI_R_wave': fields.Float,
				  'DI_S_wave': fields.Float,
				  'DI_R1_wave': fields.Float,
				  'DI_S1_wave': fields.Float,
				  'DI_no_intrinsic_defelections': fields.Float,
				  'DI_Rag_R_wave': fields.Float,
				  'DI_Dip_deriv_R_wave': fields.Float,
				  'DI_Rag_P_wave': fields.Float,
				  'DI_Dip_deriv_P_wave': fields.Float,
				  'DI_Rag_T_wave': fields.Float,
				  'DI_Dip_deriv_T_wave': fields.Float,
				  'DII_Q_wave': fields.Float,
				  'DII_R_wave': fields.Float,
				  'DII_S_wave': fields.Float,
				  'DII_R1_wave': fields.Float,
				  'DII_S1_wave': fields.Float,
				  'DII_no_intrinsic_defelections': fields.Float,
				  'DII_Rag_R_wave': fields.Float,
				  'DII_Dip_deriv_R_wave': fields.Float,
				  'DII_Rag_P_wave': fields.Float,
				  'DII_Dip_deriv_P_wave': fields.Float,
				  'DII_Rag_T_wave': fields.Float,
				  'DII_Dip_deriv_T_wave': fields.Float,
				  'DIII_Q_wave': fields.Float,
				  'DIII_R_wave': fields.Float,
				  'DIII_S_wave': fields.Float,
				  'DIII_R1_wave': fields.Float,
				  'DIII_S1_wave': fields.Float,
				  'DIII_no_intrinsic_defelections': fields.Float,
				  'DIII_Rag_R_wave': fields.Float,
				  'DIII_Dip_deriv_R_wave': fields.Float,
				  'DIII_Rag_P_wave': fields.Float,
				  'DIII_Dip_deriv_P_wave': fields.Float,
				  'DIII_Rag_T_wave': fields.Float,
				  'DIII_Dip_deriv_T_wave': fields.Float,
				  'AVR_Q_wave': fields.Float,
				  'AVR_R_wave': fields.Float,
				  'AVR_S_wave': fields.Float,
				  'AVR_R1_wave': fields.Float,
				  'AVR_S1_wave': fields.Float,
				  'AVR_no_intrinsic_defelections': fields.Float,
				  'AVR_Rag_R_wave': fields.Float,
				  'AVR_Dip_deriv_R_wave': fields.Float,
				  'AVR_Rag_P_wave': fields.Float,
				  'AVR_Dip_deriv_P_wave': fields.Float,
				  'AVR_Rag_T_wave': fields.Float,
				  'AVR_Dip_deriv_T_wave': fields.Float,
				  'AVL_Q_wave': fields.Float,
				  'AVL_R_wave': fields.Float,
				  'AVL_S_wave': fields.Float,
				  'AVL_R1_wave': fields.Float,
				  'AVL_S1_wave': fields.Float,
				  'AVL_no_intrinsic_defelections': fields.Float,
				  'AVL_Rag_R_wave': fields.Float,
				  'AVL_Dip_deriv_R_wave': fields.Float,
				  'AVL_Rag_P_wave': fields.Float,
				  'AVL_Dip_deriv_P_wave': fields.Float,
				  'AVL_Rag_T_wave': fields.Float,
				  'AVL_Dip_deriv_T_wave': fields.Float,
				  'AVF_Q_wave': fields.Float,
				  'AVF_R_wave': fields.Float,
				  'AVF_S_wave': fields.Float,
				  'AVF_R1_wave': fields.Float,
				  'AVF_S1_wave': fields.Float,
				  'AVF_no_intrinsic_defelections': fields.Float,
				  'AVF_Rag_R_wave': fields.Float,
				  'AVF_Dip_deriv_R_wave': fields.Float,
				  'AVF_Rag_P_wave': fields.Float,
				  'AVF_Dip_deriv_P_wave': fields.Float,
				  'AVF_Rag_T_wave': fields.Float,
				  'AVF_Dip_deriv_T_wave': fields.Float,
				  'V1_Q_wave': fields.Float,
				  'V1_R_wave': fields.Float,
				  'V1_S_wave': fields.Float,
				  'V1_R1_wave': fields.Float,
				  'V1_S1_wave': fields.Float,
				  'V1_no_intrinsic_defelections': fields.Float,
				  'V1_Rag_R_wave': fields.Float,
				  'V1_Dip_deriv_R_wave': fields.Float,
				  'V1_Rag_P_wave': fields.Float,
				  'V1_Dip_deriv_P_wave': fields.Float,
				  'V1_Rag_T_wave': fields.Float,
				  'V1_Dip_deriv_T_wave': fields.Float,
				  'V2_Q_wave': fields.Float,
				  'V2_R_wave': fields.Float,
				  'V2_S_wave': fields.Float,
				  'V2_R1_wave': fields.Float,
				  'V2_S1_wave': fields.Float,
				  'V2_no_intrinsic_defelections': fields.Float,
				  'V2_Rag_R_wave': fields.Float,
				  'V2_Dip_deriv_R_wave': fields.Float,
				  'V2_Rag_P_wave': fields.Float,
				  'V2_Dip_deriv_P_wave': fields.Float,
				  'V2_Rag_T_wave': fields.Float,
				  'V2_Dip_deriv_T_wave': fields.Float,
				  'V3_Q_wave': fields.Float,
				  'V3_R_wave': fields.Float,
				  'V3_S_wave': fields.Float,
				  'V3_R1_wave': fields.Float,
				  'V3_S1_wave': fields.Float,
				  'V3_no_intrinsic_defelections': fields.Float,
				  'V3_Rag_R_wave': fields.Float,
				  'V3_Dip_deriv_R_wave': fields.Float,
				  'V3_Rag_P_wave': fields.Float,
				  'V3_Dip_deriv_P_wave': fields.Float,
				  'V3_Rag_T_wave': fields.Float,
				  'V3_Dip_deriv_T_wave': fields.Float,
				  'V4_Q_wave': fields.Float,
				  'V4_R_wave': fields.Float,
				  'V4_S_wave': fields.Float,
				  'V4_R1_wave': fields.Float,
				  'V4_S1_wave': fields.Float,
				  'V4_no_intrinsic_defelections': fields.Float,
				  'V4_Rag_R_wave': fields.Float,
				  'V4_Dip_deriv_R_wave': fields.Float,
				  'V4_Rag_P_wave': fields.Float,
				  'V4_Dip_deriv_P_wave': fields.Float,
				  'V4_Rag_T_wave': fields.Float,
				  'V4_Dip_deriv_T_wave': fields.Float,
				  'V5_Q_wave': fields.Float,
				  'V5_R_wave': fields.Float,
				  'V5_S_wave': fields.Float,
				  'V5_R1_wave': fields.Float,
				  'V5_S1_wave': fields.Float,
				  'V5_no_intrinsic_defelections': fields.Float,
				  'V5_Rag_R_wave': fields.Float,
				  'V5_Dip_deriv_R_wave': fields.Float,
				  'V5_Rag_P_wave': fields.Float,
				  'V5_Dip_deriv_P_wave': fields.Float,
				  'V5_Rag_T_wave': fields.Float,
				  'V5_Dip_deriv_T_wave': fields.Float,
				  'V6_Q_wave': fields.Float,
				  'V6_R_wave': fields.Float,
				  'V6_S_wave': fields.Float,
				  'V6_R1_wave': fields.Float,
				  'V6_S1_wave': fields.Float,
				  'V6_no_intrinsic_defelections': fields.Float,
				  'V6_Rag_R_wave': fields.Float,
				  'V6_Dip_deriv_R_wave': fields.Float,
				  'V6_Rag_P_wave': fields.Float,
				  'V6_Dip_deriv_P_wave': fields.Float,
				  'V6_Rag_T_wave': fields.Float,
				  'V6_Dip_deriv_T_wave': fields.Float,
				  'Amp_DI_JJ_wave': fields.Float,
				  'Amp_DI_Q_wave': fields.Float,
				  'Amp_DI_R_wave': fields.Float,
				  'Amp_DI_S_wave': fields.Float,
				  'Amp_DI_R1_wave': fields.Float,
				  'Amp_DI_S1_wave': fields.Float,
				  'Amp_DI_P_wave': fields.Float,
				  'Amp_DI_T_wave': fields.Float,
				  'Amp_DI_QRSA': fields.Float,
				  'Amp_DI_QRSTA': fields.Float,
				  'Amp_DII_JJ_wave': fields.Float,
				  'Amp_DII_Q_wave': fields.Float,
				  'Amp_DII_R_wave': fields.Float,
				  'Amp_DII_S_wave': fields.Float,
				  'Amp_DII_R1_wave': fields.Float,
				  'Amp_DII_S1_wave': fields.Float,
				  'Amp_DII_P_wave': fields.Float,
				  'Amp_DII_T_wave': fields.Float,
				  'Amp_DII_QRSA': fields.Float,
				  'Amp_DII_QRSTA': fields.Float,
				  'Amp_DIII_JJ_wave': fields.Float,
				  'Amp_DIII_Q_wave': fields.Float,
				  'Amp_DIII_R_wave': fields.Float,
				  'Amp_DIII_S_wave': fields.Float,
				  'Amp_DIII_R1_wave': fields.Float,
				  'Amp_DIII_S1_wave': fields.Float,
				  'Amp_DIII_P_wave': fields.Float,
				  'Amp_DIII_T_wave': fields.Float,
				  'Amp_DIII_QRSA': fields.Float,
				  'Amp_DIII_QRSTA': fields.Float,
				  'Amp_AVR_JJ_wave': fields.Float,
				  'Amp_AVR_Q_wave': fields.Float,
				  'Amp_AVR_R_wave': fields.Float,
				  'Amp_AVR_S_wave': fields.Float,
				  'Amp_AVR_R1_wave': fields.Float,
				  'Amp_AVR_S1_wave': fields.Float,
				  'Amp_AVR_P_wave': fields.Float,
				  'Amp_AVR_T_wave': fields.Float,
				  'Amp_AVR_QRSA': fields.Float,
				  'Amp_AVR_QRSTA': fields.Float,
				  'Amp_AVL_JJ_wave': fields.Float,
				  'Amp_AVL_Q_wave': fields.Float,
				  'Amp_AVL_R_wave': fields.Float,
				  'Amp_AVL_S_wave': fields.Float,
				  'Amp_AVL_R1_wave': fields.Float,
				  'Amp_AVL_S1_wave': fields.Float,
				  'Amp_AVL_P_wave': fields.Float,
				  'Amp_AVL_T_wave': fields.Float,
				  'Amp_AVL_QRSA': fields.Float,
				  'Amp_AVL_QRSTA': fields.Float,
				  'Amp_AVF_JJ_wave': fields.Float,
				  'Amp_AVF_Q_wave': fields.Float,
				  'Amp_AVF_R_wave': fields.Float,
				  'Amp_AVF_S_wave': fields.Float,
				  'Amp_AVF_R1_wave': fields.Float,
				  'Amp_AVF_S1_wave': fields.Float,
				  'Amp_AVF_P_wave': fields.Float,
				  'Amp_AVF_T_wave': fields.Float,
				  'Amp_AVF_QRSA': fields.Float,
				  'Amp_AVF_QRSTA': fields.Float,
				  'Amp_V1_JJ_wave': fields.Float,
				  'Amp_V1_Q_wave': fields.Float,
				  'Amp_V1_R_wave': fields.Float,
				  'Amp_V1_S_wave': fields.Float,
				  'Amp_V1_R1_wave': fields.Float,
				  'Amp_V1_S1_wave': fields.Float,
				  'Amp_V1_P_wave': fields.Float,
				  'Amp_V1_T_wave': fields.Float,
				  'Amp_V1_QRSA': fields.Float,
				  'Amp_V1_QRSTA': fields.Float,
				  'Amp_V2_JJ_wave': fields.Float,
				  'Amp_V2_Q_wave': fields.Float,
				  'Amp_V2_R_wave': fields.Float,
				  'Amp_V2_S_wave': fields.Float,
				  'Amp_V2_R1_wave': fields.Float,
				  'Amp_V2_S1_wave': fields.Float,
				  'Amp_V2_P_wave': fields.Float,
				  'Amp_V2_T_wave': fields.Float,
				  'Amp_V2_QRSA': fields.Float,
				  'Amp_V2_QRSTA': fields.Float,
				  'Amp_V3_JJ_wave': fields.Float,
				  'Amp_V3_Q_wave': fields.Float,
				  'Amp_V3_R_wave': fields.Float,
				  'Amp_V3_S_wave': fields.Float,
				  'Amp_V3_R1_wave': fields.Float,
				  'Amp_V3_S1_wave': fields.Float,
				  'Amp_V3_P_wave': fields.Float,
				  'Amp_V3_T_wave': fields.Float,
				  'Amp_V3_QRSA': fields.Float,
				  'Amp_V3_QRSTA': fields.Float,
				  'Amp_V4_JJ_wave': fields.Float,
				  'Amp_V4_Q_wave': fields.Float,
				  'Amp_V4_R_wave': fields.Float,
				  'Amp_V4_S_wave': fields.Float,
				  'Amp_V4_R1_wave': fields.Float,
				  'Amp_V4_S1_wave': fields.Float,
				  'Amp_V4_P_wave': fields.Float,
				  'Amp_V4_T_wave': fields.Float,
				  'Amp_V4_QRSA': fields.Float,
				  'Amp_V4_QRSTA': fields.Float,
				  'Amp_V5_JJ_wave': fields.Float,
				  'Amp_V5_Q_wave': fields.Float,
				  'Amp_V5_R_wave': fields.Float,
				  'Amp_V5_S_wave': fields.Float,
				  'Amp_V5_R1_wave': fields.Float,
				  'Amp_V5_S1_wave': fields.Float,
				  'Amp_V5_P_wave': fields.Float,
				  'Amp_V5_T_wave': fields.Float,
				  'Amp_V5_QRSA': fields.Float,
				  'Amp_V5_QRSTA': fields.Float,
				  'Amp_V6_JJ_wave': fields.Float,
				  'Amp_V6_Q_wave': fields.Float,
				  'Amp_V6_R_wave': fields.Float,
				  'Amp_V6_S_wave': fields.Float,
				  'Amp_V6_R1_wave': fields.Float,
				  'Amp_V6_S1_wave': fields.Float,
				  'Amp_V6_P_wave': fields.Float,
				  'Amp_V6_T_wave': fields.Float,
				  'Amp_V6_QRSA': fields.Float,
				  'Amp_V6_QRSTA': fields.Float})


classifier = joblib.load('heart_disease.joblib')

@name_space.route("/")
class MainClass(Resource):

	def options(self):
		response = make_response()
		response.headers.add("Access-Control-Allow-Origin", "*")
		response.headers.add('Access-Control-Allow-Headers', "*")
		response.headers.add('Access-Control-Allow-Methods', "*")
		return response

	@app.expect(model)		
	def post(self):
		try: 
			formData = request.json
			data = [val for val in formData.values()]
			data.replace([np.inf, -np.inf], np.nan)
			data.dropna(inplace=True)
			prediction = classifier.predict(np.array(data).reshape(1, -1))
			types = { 1: "Normal", 2: "CAD", 3: "AMI",4:"IMI",5:"T",6:"B",7:"PVC",8:"PSC",9:"LBB",10:"RBB",14:"LVH",15:"AF",16:"others"}
			response = jsonify({
				"statusCode": 200,
				"status": "Prediction made",
				"result": "Diagnosis: " + types[prediction[0]]
				})
			response.headers.add('Access-Control-Allow-Origin', '*')
			return response
		except Exception as error:
			return jsonify({
				"statusCode": 500,
				"status": "Could not make prediction",
				"error": str(error)
			})

   